<a href="https://colab.research.google.com/github/krish-thorcode/Deep-Learning_A-Z/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing libraries

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing dataset

In [0]:
df = pd.read_csv('./drive/My Drive/Colab Notebooks/DL_A-Z/Churn_Modelling.csv')

In [5]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

#### We do not need RowNumber, CustomerId, Surname in our dataset as they do not actually contribute to the depended variable.

In [0]:
x = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [7]:
x.shape, y.shape

((10000, 10), (10000,))

## Encoding categorical data

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
print(x[0:10])

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 'Male' 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 'Male' 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 'Female' 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 'Male' 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 'Male' 27 2 134603.88 1 1 1 71725.73]]


In [0]:
labelencoder_X_country = LabelEncoder()
x[:, 1] = labelencoder_X_country.fit_transform(x[:, 1])

In [12]:
print(x[:2])

[[619 0 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 2 'Female' 41 1 83807.86 1 0 1 112542.58]]


In [0]:
labelencoder_X_gender = LabelEncoder()
x[:, 2] = labelencoder_X_gender.fit_transform(x[:, 2])

In [14]:
print(x[:10])

[[619 0 0 42 2 0.0 1 1 1 101348.88]
 [608 2 0 41 1 83807.86 1 0 1 112542.58]
 [502 0 0 42 8 159660.8 3 1 0 113931.57]
 [699 0 0 39 1 0.0 2 0 0 93826.63]
 [850 2 0 43 2 125510.82 1 1 1 79084.1]
 [645 2 1 44 8 113755.78 2 1 0 149756.71]
 [822 0 1 50 7 0.0 2 1 1 10062.8]
 [376 1 0 29 4 115046.74 4 1 0 119346.88]
 [501 0 1 44 4 142051.07 2 0 1 74940.5]
 [684 0 1 27 2 134603.88 1 1 1 71725.73]]


We onehot-encode only the Geography attribute values because it contains three distinct values (LabelEncoded into (0, 1, 2)). Later we shall remove one of the three columns generated by onehotencoding of Geography attribute to avoid the dummy variable trap. In case of Gender , which has only two values possible, we do not have to onehot-encode it as if done so, its values will be mapped to the set {0, 1}. In turn, we shall have to eliminate one column from the onehot representation of gender to counter the dummy varible trap. Doing this is essentially the same as stopping at LabelEncoding.

In [15]:
onehotencoder = OneHotEncoder(categorical_features = [1])
x = onehotencoder.fit_transform(x).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
np.set_printoptions(precision=3, suppress=True)
print(x[:2])

[[     1.        0.        0.      619.        0.       42.        2.
       0.        1.        1.        1.   101348.88]
 [     0.        0.        1.      608.        0.       41.        1.
   83807.86      1.        0.        1.   112542.58]]


## Escaping the Dummy Variable Trap

In [0]:
x = x[:, 1:]

## Split into train and test set

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

## Feature scaling

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
standard_scaler = StandardScaler()

In [0]:
x_train = standard_scaler.fit_transform(x_train)
x_test = standard_scaler.fit_transform(x_test)

## Making the ANN

In [23]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
classifier = Sequential()

In [25]:
x.shape

(10000, 11)

In [26]:
classifier.add(Dense(input_dim=11, init='uniform', activation='relu', output_dim=6))

Instructions for updating:
Colocations handled automatically by placer.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [27]:
classifier.add(Dense(init='uniform', activation='relu', output_dim=6))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [28]:
classifier.add(Dense(init='uniform', activation='sigmoid', output_dim=1))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
classifier.fit(x_train, y_train, batch_size=10, nb_epoch=100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4827 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4283 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4225 - acc: 0.7975
Epoch 4/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4184 - acc: 0.8214
Epoch 5/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.4164 - acc: 0.8272
Epoch 6/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.4143 - acc: 0.8310
Epoch 7/100
8000/8000 [==============================] - 1s 96us/step - loss: 0.4131 - acc: 0.8311
Epoch 8/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4121 - acc: 0.8332
Epoch 9/100
8000/8000 [==============================] - 1s 94us/step - loss: 0.4115 - acc: 0.8326
Epoch 10/100
8000/8000 [==============================] - 1s

In [0]:
y_pred = classifier.predict(x_test)

## Evaluating the model

In [0]:
from sklearn.metrics import confusion_matrix

In [37]:
print(y_pred[:4])

[[0.175]
 [0.363]
 [0.133]
 [0.047]]


In [0]:
y_pred = y_pred > 0.5

In [0]:
confusion_mat = confusion_matrix(y_test, y_pred)

In [0]:
test_accuracy = (confusion_mat[0, 0] + confusion_mat[1,1])/np.sum(confusion_mat)

In [42]:

test_accuracy

0.8385

## Assignment

### Test example is represented with following set of attributes:

Geography: France <br>
Credit score: 600<br>
Gender: Male<br>
Age: 40<br>
Tenure: 3<br>
Balance: 60000<br>
Number of Products: 2<br>
Has Credit Card: Yes<br>
Is Active Member: Yes<br>
Estimated Salary: 50000<br>


From the dataset used during training phase, we can see that France is represented by the onehotencoded dummy variable values (0, 0) and Male is represented by 1 (labelencoder). Also, in the training dataset, Has Credit Card contains values from the set {0, 1} (0-No, 1-Yes).

In [45]:
test_example = np.array([[0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])
test_example = standard_scaler.transform(test_example)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [0]:
test_pred = classifier.predict(test_example)

In [48]:
test_pred

array([[0.074]], dtype=float32)

In [50]:

test_pred = test_pred>0.5
print(test_pred)

[[False]]


## Transition to the next topic
Retraining this very same model again, without changing any piece of code, may result in different training and test accuracies because of the fact that the weight initialisation is done randomly (from a uniform distribution in this case). We do not have any feature that can allow us to fix a 'seed value' (like we did in train_test_split function) to control the way random initialisation is done.

It turns out that because of the above reason, evaluating a model the way we've done above is not the right way to do it. In the next model, we shall have a look on how the performance of models can/should be evaluated.